### ISSUE TITLE
filter function not working

### ISSUE THREAD

**Issue by thigm85** [sbfnk/RBi#13]
When trying to use the `filter` function with a `libbi` object I get the following error:
```
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "libbi"
```
The error can be replicated by running 
``` 
demo(PZ_filtering)
```
Is this a known issue?

**Comment by sbfnk** [comment]
This sounds like you've loaded another package that has redefined rbi's `filter` function (e.g., dplyr). If, when the error occurs, you copy the line where the error occurs and qualify the `filter` function, does it work?

```
bi_object <- rbi::filter(bi_object, nparticles = 8192, nthreads = 1, end_time = T, noutputs = T,
                         obs = synthetic_dataset, init = init_parameters)
```

**Comment by thigm85** [comment]
Perfect. Using `rbi::` worked.
