### ISSUE TITLE
Passing Inputs as a list and the new force_inputs option.

### ISSUE THREAD

**Issue by seabbs** [sbfnk/RBi#16]
Hi Seb, 

First off, great package! Thanks for all the hard work.

Just updated to the latest GitHub version and I am seeing an error with my inputs not being found by Libbi. I have been passing them in as a named list of data frames and everything has been working as expected up to now.

Looking at your latest series of commits I see that a force_inputs option has been added for use with input files. Setting this to be false (rather than the default true) gets me back to everything working properly. Not sure if this is a bug or if passing inputs as a list is being deprecated!

Happy to knock up an example if useful.

Thanks, 

Sam

**Comment by sbfnk** [comment]
You're right - this change is causing some problems with input files. I'll have a look at fixing this. In the meantime, setting `force_inputs=FALSE` is a good workaround.
