### ISSUE TITLE
How to add cuda-arch option

### ISSUE THREAD

**Issue by seabbs** [sbfnk/RBi#21]
Hi Seb, 

Trying to use the `--cuda-arch` option via Libbi. Based on the current `run.libbi` help I am not sure this is possible. Using `cuda-arch = TRUE` leads to an error as this is formatted as `enable-cuda-arch` which doesn't exist. 

If this is a bug/omission I am happy to fix in a pull request (pointers in the code would be useful). 

Thanks, 

Sam

**Comment by sbfnk** [comment]
The `--cuda-arch` takes a string, one of the ones listed on the [cuda driver help page](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list). Can you try, e.g., `cuda_arch="sm_30"`?
