### ISSUE TITLE
Flagging {tidync} - "tidy" handling of NetCDF

### ISSUE THREAD

**Issue by seabbs** [sbfnk/RBi#22]
Hi Seb, 

Just flagging [this](https://ropensci.org/blog/2019/11/05/tidync/) Ropensci package for handling NetCDF data in a "tidy" way.  I assume that there would be little to gain from moving to this for handling the NetCDF read/writes but thought it worth bringing to your attention (though you were probably already aware :smile:)

Happy to help with any conversion work if this is of interest.

**Comment by sbfnk** [comment]
Thanks for the flag.
