### ISSUE TITLE
Can not install LibBi

### ISSUE THREAD

**Issue by NedaJalali-codes** [sbfnk/RBi#23]
Hi,
I am trying to install LibBi from "LibBi-stable.tar.gz" in R studio but this error comes up:
"ERROR: cannot extract the package from 'LibBi-stable.tar.gz'"

Can you help me with this issue? 

Best,
Neda

**Comment by sbfnk** [comment]
Please try installing with `install.packages("rbi")` or `remotes::install_github("sbfnk/rbi")`
