### ISSUE TITLE
Error messages in the Introduction to RBi vignette

### ISSUE THREAD

**Issue by chrisprashad** [sbfnk/RBi#29]
**Context:**

In the [RBi package vignette](https://cran.r-project.org/web/packages/rbi/vignettes/introduction.html), under **Generating a dataset**, there is the following error message: 

```
## Error in run.libbi(x, client = "sample", ...): LibBi terminated with "Error: ./configure failed with return code 77. See /var/folders/k_/8wrb49vn4713j7fn6y3hmndm0000gn/T/Rtmpjgq4OD/SIR1336d7948851c/.SIR/build_assert_openmp_sm_30/configure.log and /var/folders/k_/8wrb49vn4713j7fn6y3hmndm0000gn/T/Rtmpjgq4OD/SIR1336d7948851c/.SIR/build_assert_openmp_sm_30/config.log for details".
## You can view a full log using "print_log('/private/var/folders/k_/8wrb49vn4713j7fn6y3hmndm0000gn/T/Rtmpjgq4OD/SIR1336d7948851c/output1336d81b2f79.txt')"
```

All subsequent commands also yield errors as a result and no useful output is generated.

I would appreciate if you could assist with resolving this issue.

**Comment by sbfnk** [comment]
Can you run the `print_log` command that's suggested and post the output?

**Comment by sbfnk** [comment]
Closing as stale. @chrisprashad please reopen if you still have this issue.
