### ISSUE TITLE
 Could not find libbi executable at '/libbi'

### ISSUE THREAD

**Issue by Laplace3210** [sbfnk/RBi#32]
When I excuted the sample fuction, there is an error like that, how should I solve it?

![1670853554619](https://user-images.githubusercontent.com/50813700/207063915-54f7d899-6cf8-4ad0-b110-da68b6a52f38.png)

**Comment by sbfnk** [comment]
I think you need to make sure that LibBi is installed - please reopen if you are still having problems with this.
