### ISSUE TITLE
Rbi.helpers-How to discard burn-in correctly?

### ISSUE THREAD

**Issue by MollyCYM** [sbfnk/rbi#33]
In some simulation experiments, we want to check if the posterior samples correctly start from the initial values we assign to each parameter. The current way we did this is to first set the initial values of parameters using init in sample function, then remove the adapt_proposal line in our code and followed with sample(nsamples=10000, thin=1). But the resulting trace plot tells us this seems to be incorrect (e.g. tau’s initial value is set to be 0.8, but from the trace plot, it starts from 0.3 ). So is there a way to correctly discard burn-in in LibBi?
<img width="497" alt="Screenshot 2023-05-24 at 11 33 49" src="https://github.com/sbfnk/RBi/assets/78714427/516c47c4-d0bb-49b3-96a6-98d171d2978b">

**Comment by sbfnk** [comment]
Hi, and thanks for raising this. Can you provide a reproducible example, please? You could, e.g., use the `reprex` package: https://reprex.tidyverse.org/

**Comment by sbfnk** [comment]
Closing this for now as we won’t be able to comment on this without a reproducible code example. Please reopen with a code example if this issue persists.
